import type { Metadata } from "next";
import { Roboto_Flex } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import StoreProvider from "./storeProvider";

const roboto = Roboto_Flex({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className={`${roboto.className} w-full`}>
          <div className="w-full flex flex-col items-center font-roboto">
            <div className="max-w-[1440px] w-full overflow-hidden flex flex-col items-center min-h-dvh relative">
              <Header />
              <div className="w-full">{children}</div>
              <Footer />
            </div>
          </div>
        </body>
      </StoreProvider>
    </html>
  );
}
